if v:progname =~? "evim"
    finish
endif

" Use old regex engine for speed
if v:version >= 704
    set re=1
endif

set ttyfast
set lazyredraw

call pathogen#infect()
" work's env sets term to something dumb. Make vim not care.
" set term=xterm

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" This is usually the default except in OpenBSD's port somehow
set backspace=indent,eol,start

" Avoids "warning ... changed since reading" warnings
set autoread

" Make shift-insert work like in Xterm
map <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>

set nobackup
set history=1000
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set cmdheight=2

" Line Wrap stuff
set wrap        " wrap lines

" Disable vim help
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

set cursorline  " highlights the current line

" Way better command completion
set wildmenu
set wildmode=longest:full,list:full
set wildignore=*.swp,*.bak,*.pyc,*.class

" Have to wait for Terminal.app to support true color for this:
" set termguicolors
set t_Co=256
syntax on
set bg=light
let g:gruvbox_contrast_dark='hard'
let g:gruvbox_contrast_light='hard'
colorscheme gruvbox
" Don't draw a bgcolor (let the terminal choose it)
highlight Normal ctermbg=none

set autoindent		" always set autoindenting on
set nohlsearch
set noincsearch

set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set cino=N-s " don't indent namespaces in C++

filetype indent on

au BufNewFile,BufRead *.htmlt set filetype=html
au BufNewFile,BufRead *.asm set filetype=nasm
au BufNewFile,BufRead *.go set filetype=go
au BufNewFile,BufRead *.pp set filetype=puppet
au BufNewFile,BufRead *.coffee set filetype=coffee
au BufNewFile,BufRead *.coffee.erb set filetype=coffee
au BufNewFile,BufRead *.rabl set filetype=ruby
au BufNewFile,BufRead Capfile set filetype=ruby
au BufNewFile,BufRead Gemfile set filetype=ruby
au BufNewFile,BufRead Podfile set filetype=ruby
au BufNewFile,BufRead *.rb set filetype=ruby
au BufNewFile,BufRead *.vp,*.fp,*.gp,*.vs,*.fs,*.gs,*.tcs,*.tes,*.vert,*.frag,*.geom,*.tess,*.shd,*.gls,*.glsl set ft=glsl330

autocmd FileType ruby,puppet,yaml,javascript set sw=2 ts=2 et
autocmd FileType make,jade set noet
autocmd FileType go set ts=8 sw=8 noet


" Clear treailing whitespace for some languages
autocmd FileType ruby,puppet,coffee,go autocmd BufWritePre <buffer> :%s/\s\+$//e

" Custom commands
map <Space> <Leader>
map , <Leader>
map <Leader>, :NERDTreeToggle<cr>
map <Leader><Space> :NERDTreeToggle<cr>
map <Leader>f :NERDTreeFind<cr>
map <silent> <Leader>b :BufExplorer<cr>
map <silent> <Leader>s :split<cr>


" Buffer switching easier
set hidden
map <C-right> :bnext<cr>
map <C-left> :bprev<cr>

" Better comment formatting defaults
set formatoptions+=r

if has('patch541')
  set formatoptions+=j
end

" Prevent the global gvimrc for macvim (/Applications/MacVim/.../gvimrc) from
" setting colorscheme and overriding what we set here.
let macvim_skip_colorscheme=1
"set transparency=10

" Inspect color under cursor for color scheme debugging
map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<' . synIDattr(synID(line("."),col("."),0),"name") . "> lo<" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">" . " FG:" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"fg#")<CR>

let &titlestring = hostname() . "[vim(" . expand("%:t") . ")]"
if &term == "screen"
  set t_ts=k
  set t_fs=\
endif
if &term == "screen" || &term == "xterm"
  set title
endif

auto VimLeave * :set t_ts=k.\
" The only correct unicode encoding.
set encoding=utf-8

if has("gui_running")
    set mouse=a
    set guioptions-=T

    " Simple copy/paste (visual mode only)
    vmap <C-S-C> "+y
    vmap <C-C> "+y

    " ctrl+shift+v pastes in any mode
    map <C-S-V> "+P
    imap <C-S-V> <C-r><C-o>+

    " ctrl+v pastes in insert mode only (else conflicts with block select)
    imap <C-V> <C-r><C-o>+
else
    " In cli I'd rather have my terminal emulator do things like selection
    set mouse=
endif
"map <ScrollWheelUp> <C-Y>
"map <ScrollWheelDown> <C-E>

" Set bufexplorer options so that <Leader>b just goes straight to a horizontal split
let g:bufExplorerDisableDefaultKeyMapping=1
let g:bufExplorerFindActive=1

let g:ctrlp_custom_ignore = {
  \ 'dir': '\v[\/]((\.git|\.hg|\.svn)|node_modules|vendor)$'
  \}
let g:ctrlp_max_files=100000

filetype plugin on

" I hate folding.
set nofoldenable

" disable bells in gvim/macvim
"
set t_vb=
set visualbell

" Rust stuff
let g:rustfmt_autosave = 1

" Prevent ObjC indentation from trying to align colons (it's bad at it.)
function GetObjCIndent()
    let theIndent = cindent(v:lnum)
    return theIndent
endfunction

if filereadable($HOME . "/.vim/local.vim")
    execute 'source' $HOME . "/.vim/local.vim"
end
